/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
/* tslint:disable */
"use strict";
exports.styles = ['[_nghost-%COMP%]{\n    width:100%;\n    position: absolute;\n    display: block;\n    left:0;\n}'];
//# sourceMappingURL=blogs.view.css.shim.js.map