/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '@angular/common/src/localization';
import * as import9 from '@angular/core/src/application_init';
import * as import10 from '@angular/core/src/testability/testability';
import * as import11 from '@angular/core/src/application_ref';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/platform-browser/src/browser/title';
import * as import20 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import21 from '@angular/common/src/location/location';
import * as import22 from '@angular/router/src/url_tree';
import * as import23 from '@angular/router/src/router_outlet_map';
import * as import24 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import25 from '@angular/core/src/di/injector';
import * as import26 from './blogs.component.ngfactory';
import * as import27 from './cv.component.ngfactory';
import * as import28 from './app.component.ngfactory';
import * as import29 from '@angular/core/src/application_tokens';
import * as import30 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import31 from '@angular/platform-browser/src/dom/events/key_events';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import34 from '@angular/common/src/location/platform_location';
import * as import35 from '@angular/common/src/location/location_strategy';
import * as import36 from '../../app/blogs.component';
import * as import37 from '../../app/cv.component';
import * as import38 from '@angular/router/src/router';
import * as import39 from '@angular/core/src/console';
import * as import40 from '@angular/core/src/i18n/tokens';
import * as import41 from '@angular/core/src/error_handler';
import * as import42 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import43 from '@angular/platform-browser/src/dom/animation_driver';
import * as import44 from '@angular/core/src/render/api';
import * as import45 from '@angular/core/src/security';
import * as import46 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import47 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import48 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import49 from '@angular/router/src/router_config_loader';
import * as import50 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _AppModule_7:import1.AppModule;
  __LOCALE_ID_8:any;
  __NgLocalization_9:import8.NgLocaleLocalization;
  _ErrorHandler_10:any;
  _ApplicationInitStatus_11:import9.ApplicationInitStatus;
  _Testability_12:import10.Testability;
  _ApplicationRef__13:import11.ApplicationRef_;
  __ApplicationRef_14:any;
  __Compiler_15:import12.Compiler;
  __APP_ID_16:any;
  __DOCUMENT_17:any;
  __HAMMER_GESTURE_CONFIG_18:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_19:any[];
  __EventManager_20:import14.EventManager;
  __DomSharedStylesHost_21:import15.DomSharedStylesHost;
  __AnimationDriver_22:any;
  __DomRootRenderer_23:import16.DomRootRenderer_;
  __RootRenderer_24:any;
  __DomSanitizer_25:import17.DomSanitizerImpl;
  __Sanitizer_26:any;
  __ViewUtils_27:import18.ViewUtils;
  __IterableDiffers_28:any;
  __KeyValueDiffers_29:any;
  __SharedStylesHost_30:any;
  __Title_31:import19.Title;
  __RadioControlRegistry_32:import20.RadioControlRegistry;
  __ROUTER_CONFIGURATION_33:any;
  __LocationStrategy_34:any;
  __Location_35:import21.Location;
  __UrlSerializer_36:import22.DefaultUrlSerializer;
  __RouterOutletMap_37:import23.RouterOutletMap;
  __NgModuleFactoryLoader_38:import24.SystemJsNgModuleLoader;
  __ROUTES_39:any[];
  __Router_40:any;
  __ActivatedRoute_41:any;
  __APP_BOOTSTRAP_LISTENER_42:any[];
  constructor(parent:import25.Injector) {
    super(parent,[
      import26.BlogsComponentNgFactory,
      import27.CvComponentNgFactory,
      import28.AppComponentNgFactory
    ]
    ,[import28.AppComponentNgFactory]);
  }
  get _LOCALE_ID_8():any {
    if ((this.__LOCALE_ID_8 == (null as any))) { (this.__LOCALE_ID_8 = 'en-US'); }
    return this.__LOCALE_ID_8;
  }
  get _NgLocalization_9():import8.NgLocaleLocalization {
    if ((this.__NgLocalization_9 == (null as any))) { (this.__NgLocalization_9 = new import8.NgLocaleLocalization(this._LOCALE_ID_8)); }
    return this.__NgLocalization_9;
  }
  get _ApplicationRef_14():any {
    if ((this.__ApplicationRef_14 == (null as any))) { (this.__ApplicationRef_14 = this._ApplicationRef__13); }
    return this.__ApplicationRef_14;
  }
  get _Compiler_15():import12.Compiler {
    if ((this.__Compiler_15 == (null as any))) { (this.__Compiler_15 = new import12.Compiler()); }
    return this.__Compiler_15;
  }
  get _APP_ID_16():any {
    if ((this.__APP_ID_16 == (null as any))) { (this.__APP_ID_16 = import29._appIdRandomProviderFactory()); }
    return this.__APP_ID_16;
  }
  get _DOCUMENT_17():any {
    if ((this.__DOCUMENT_17 == (null as any))) { (this.__DOCUMENT_17 = import4._document()); }
    return this.__DOCUMENT_17;
  }
  get _HAMMER_GESTURE_CONFIG_18():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_18 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_18 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_18;
  }
  get _EVENT_MANAGER_PLUGINS_19():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_19 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_19 = [
      new import30.DomEventsPlugin(),
      new import31.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_18)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_19;
  }
  get _EventManager_20():import14.EventManager {
    if ((this.__EventManager_20 == (null as any))) { (this.__EventManager_20 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_19,this.parent.get(import32.NgZone))); }
    return this.__EventManager_20;
  }
  get _DomSharedStylesHost_21():import15.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_21 == (null as any))) { (this.__DomSharedStylesHost_21 = new import15.DomSharedStylesHost(this._DOCUMENT_17)); }
    return this.__DomSharedStylesHost_21;
  }
  get _AnimationDriver_22():any {
    if ((this.__AnimationDriver_22 == (null as any))) { (this.__AnimationDriver_22 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_22;
  }
  get _DomRootRenderer_23():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_23 == (null as any))) { (this.__DomRootRenderer_23 = new import16.DomRootRenderer_(this._DOCUMENT_17,this._EventManager_20,this._DomSharedStylesHost_21,this._AnimationDriver_22)); }
    return this.__DomRootRenderer_23;
  }
  get _RootRenderer_24():any {
    if ((this.__RootRenderer_24 == (null as any))) { (this.__RootRenderer_24 = import33._createConditionalRootRenderer(this._DomRootRenderer_23,this.parent.get(import33.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_24;
  }
  get _DomSanitizer_25():import17.DomSanitizerImpl {
    if ((this.__DomSanitizer_25 == (null as any))) { (this.__DomSanitizer_25 = new import17.DomSanitizerImpl()); }
    return this.__DomSanitizer_25;
  }
  get _Sanitizer_26():any {
    if ((this.__Sanitizer_26 == (null as any))) { (this.__Sanitizer_26 = this._DomSanitizer_25); }
    return this.__Sanitizer_26;
  }
  get _ViewUtils_27():import18.ViewUtils {
    if ((this.__ViewUtils_27 == (null as any))) { (this.__ViewUtils_27 = new import18.ViewUtils(this._RootRenderer_24,this._APP_ID_16,this._Sanitizer_26)); }
    return this.__ViewUtils_27;
  }
  get _IterableDiffers_28():any {
    if ((this.__IterableDiffers_28 == (null as any))) { (this.__IterableDiffers_28 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_28;
  }
  get _KeyValueDiffers_29():any {
    if ((this.__KeyValueDiffers_29 == (null as any))) { (this.__KeyValueDiffers_29 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_29;
  }
  get _SharedStylesHost_30():any {
    if ((this.__SharedStylesHost_30 == (null as any))) { (this.__SharedStylesHost_30 = this._DomSharedStylesHost_21); }
    return this.__SharedStylesHost_30;
  }
  get _Title_31():import19.Title {
    if ((this.__Title_31 == (null as any))) { (this.__Title_31 = new import19.Title()); }
    return this.__Title_31;
  }
  get _RadioControlRegistry_32():import20.RadioControlRegistry {
    if ((this.__RadioControlRegistry_32 == (null as any))) { (this.__RadioControlRegistry_32 = new import20.RadioControlRegistry()); }
    return this.__RadioControlRegistry_32;
  }
  get _ROUTER_CONFIGURATION_33():any {
    if ((this.__ROUTER_CONFIGURATION_33 == (null as any))) { (this.__ROUTER_CONFIGURATION_33 = {}); }
    return this.__ROUTER_CONFIGURATION_33;
  }
  get _LocationStrategy_34():any {
    if ((this.__LocationStrategy_34 == (null as any))) { (this.__LocationStrategy_34 = import7.provideLocationStrategy(this.parent.get(import34.PlatformLocation),this.parent.get(import35.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_33)); }
    return this.__LocationStrategy_34;
  }
  get _Location_35():import21.Location {
    if ((this.__Location_35 == (null as any))) { (this.__Location_35 = new import21.Location(this._LocationStrategy_34)); }
    return this.__Location_35;
  }
  get _UrlSerializer_36():import22.DefaultUrlSerializer {
    if ((this.__UrlSerializer_36 == (null as any))) { (this.__UrlSerializer_36 = new import22.DefaultUrlSerializer()); }
    return this.__UrlSerializer_36;
  }
  get _RouterOutletMap_37():import23.RouterOutletMap {
    if ((this.__RouterOutletMap_37 == (null as any))) { (this.__RouterOutletMap_37 = new import23.RouterOutletMap()); }
    return this.__RouterOutletMap_37;
  }
  get _NgModuleFactoryLoader_38():import24.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_38 == (null as any))) { (this.__NgModuleFactoryLoader_38 = new import24.SystemJsNgModuleLoader(this._Compiler_15,this.parent.get(import24.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_38;
  }
  get _ROUTES_39():any[] {
      if ((this.__ROUTES_39 == (null as any))) { (this.__ROUTES_39 = [[
        {
          path: 'blogs',
          component: import36.BlogsComponent
        }
        ,
        {
          path: 'cv',
          component: import37.CvComponent
        }
        ,
        {
          path: '',
          redirectTo: '/blogs',
          pathMatch: 'full'
        }

      ]
    ]); }
    return this.__ROUTES_39;
  }
  get _Router_40():any {
    if ((this.__Router_40 == (null as any))) { (this.__Router_40 = import7.setupRouter(this._ApplicationRef_14,this._UrlSerializer_36,this._RouterOutletMap_37,this._Location_35,this,this._NgModuleFactoryLoader_38,this._Compiler_15,this._ROUTES_39,this._ROUTER_CONFIGURATION_33)); }
    return this.__Router_40;
  }
  get _ActivatedRoute_41():any {
    if ((this.__ActivatedRoute_41 == (null as any))) { (this.__ActivatedRoute_41 = import7.rootRoute(this._Router_40)); }
    return this.__ActivatedRoute_41;
  }
  get _APP_BOOTSTRAP_LISTENER_42():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_42 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_42 = [import7.initialRouterNavigation(this._Router_40,this._ROUTER_CONFIGURATION_33)]); }
    return this.__APP_BOOTSTRAP_LISTENER_42;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import38.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._AppModule_7 = new import1.AppModule();
    this._ErrorHandler_10 = import4.errorHandler();
    this._ApplicationInitStatus_11 = new import9.ApplicationInitStatus(this.parent.get(import9.APP_INITIALIZER,(null as any)));
    this._Testability_12 = new import10.Testability(this.parent.get(import32.NgZone));
    this._ApplicationRef__13 = new import11.ApplicationRef_(this.parent.get(import32.NgZone),this.parent.get(import39.Console),this,this._ErrorHandler_10,this,this._ApplicationInitStatus_11,this.parent.get(import10.TestabilityRegistry,(null as any)),this._Testability_12);
    return this._AppModule_7;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import1.AppModule)) { return this._AppModule_7; }
    if ((token === import40.LOCALE_ID)) { return this._LOCALE_ID_8; }
    if ((token === import8.NgLocalization)) { return this._NgLocalization_9; }
    if ((token === import41.ErrorHandler)) { return this._ErrorHandler_10; }
    if ((token === import9.ApplicationInitStatus)) { return this._ApplicationInitStatus_11; }
    if ((token === import10.Testability)) { return this._Testability_12; }
    if ((token === import11.ApplicationRef_)) { return this._ApplicationRef__13; }
    if ((token === import11.ApplicationRef)) { return this._ApplicationRef_14; }
    if ((token === import12.Compiler)) { return this._Compiler_15; }
    if ((token === import29.APP_ID)) { return this._APP_ID_16; }
    if ((token === import42.DOCUMENT)) { return this._DOCUMENT_17; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_18; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_19; }
    if ((token === import14.EventManager)) { return this._EventManager_20; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_21; }
    if ((token === import43.AnimationDriver)) { return this._AnimationDriver_22; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_23; }
    if ((token === import44.RootRenderer)) { return this._RootRenderer_24; }
    if ((token === import17.DomSanitizer)) { return this._DomSanitizer_25; }
    if ((token === import45.Sanitizer)) { return this._Sanitizer_26; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_27; }
    if ((token === import46.IterableDiffers)) { return this._IterableDiffers_28; }
    if ((token === import47.KeyValueDiffers)) { return this._KeyValueDiffers_29; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_30; }
    if ((token === import19.Title)) { return this._Title_31; }
    if ((token === import20.RadioControlRegistry)) { return this._RadioControlRegistry_32; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_33; }
    if ((token === import35.LocationStrategy)) { return this._LocationStrategy_34; }
    if ((token === import21.Location)) { return this._Location_35; }
    if ((token === import22.UrlSerializer)) { return this._UrlSerializer_36; }
    if ((token === import23.RouterOutletMap)) { return this._RouterOutletMap_37; }
    if ((token === import48.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_38; }
    if ((token === import49.ROUTES)) { return this._ROUTES_39; }
    if ((token === import38.Router)) { return this._Router_40; }
    if ((token === import50.ActivatedRoute)) { return this._ActivatedRoute_41; }
    if ((token === import29.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_42; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__13.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);