/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/core/src/animation/animation_transition';
import * as import11 from '@angular/core/src/animation/animation_style_util';
import * as import12 from '@angular/core/src/animation/animation_sequence_player';
import * as import13 from '@angular/core/src/animation/animation_styles';
import * as import14 from '@angular/core/src/animation/animation_keyframe';
import * as import15 from '@angular/core/src/animation/animation_player';
import * as import16 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import17 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import18 from '@angular/router/src/router';
import * as import19 from '@angular/router/src/router_state';
import * as import20 from '@angular/common/src/location/location_strategy';
import * as import21 from '@angular/router/src/router_outlet_map';
import * as import22 from '@angular/core/src/linker/component_factory_resolver';
import * as import23 from '@angular/router/src/directives/router_link';
import * as import24 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.AppComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'my-app',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import9.ComponentFactory<import0.AppComponent> = new import9.ComponentFactory<import0.AppComponent>('my-app',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ['.nav[_ngcontent-%COMP%]{\n    position: fixed;\n    left:0;\n    top:40%;\n    z-index: 100;\n}\n\n.showMenuBtn[_ngcontent-%COMP%]{\n    position: fixed;\n    left:15px;\n    top:15px;\n    z-index: 100;\n}'];
var AppComponent_menuAnimation_states:any = {
  hide: {
    opacity: 0,
    transform: 'translateX(-100%)'
  }
  ,
  show: {
    opacity: 1,
    transform: 'translateX(0)'
  }
  ,
  '*': {}
}
;
function AppComponent_menuAnimation_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import10.AnimationTransition {
  view.animationContext.cancelActiveAnimation(element,'menuAnimation',(nextState == 'void'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = AppComponent_menuAnimation_states['*'];
  var startStateStyles:any = AppComponent_menuAnimation_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = AppComponent_menuAnimation_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  import11.renderStyles(element,view.renderer,import11.clearStyles(startStateStyles));
  if (((player == (null as any)) && ((currentState == 'hide') && (nextState == 'show')))) {
      player = new import12.AnimationSequencePlayer([view.renderer.animate(element,new import13.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import14.AnimationKeyframe(0,new import13.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import14.AnimationKeyframe(1,new import13.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,'ease-in')]);
    totalTime = 500;
  }
  if (((player == (null as any)) && ((currentState == 'show') && (nextState == 'hide')))) {
      player = new import12.AnimationSequencePlayer([view.renderer.animate(element,new import13.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import14.AnimationKeyframe(0,new import13.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import14.AnimationKeyframe(1,new import13.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,'ease-in')]);
    totalTime = 500;
  }
  if ((player == (null as any))) { (player = new import15.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    import11.renderStyles(element,view.renderer,import11.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  view.animationContext.queueAnimation(element,'menuAnimation',player);
  return new import10.AnimationTransition(player,currentState,nextState,totalTime);
}
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _RouterLinkWithHref_8_3:import16.Wrapper_RouterLinkWithHref;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import16.Wrapper_RouterLinkWithHref;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _RouterOutlet_20_5:import17.Wrapper_RouterOutlet;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_1,'div',new import4.InlineArray2(2,'class','nav'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_3,'h1',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_3,'a',new import4.InlineArray2(2,'routerLink','/blogs'),(null as any));
    this._RouterLinkWithHref_8_3 = new import16.Wrapper_RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._text_9 = this.renderer.createText(this._el_8,'Blogs',(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_3,'a',new import4.InlineArray2(2,'routerLink','/cv'),(null as any));
    this._RouterLinkWithHref_11_3 = new import16.Wrapper_RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._text_12 = this.renderer.createText(this._el_11,'CV',(null as any));
    this._text_13 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_3,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_1,'button',new import4.InlineArray2(2,'class','btn showMenuBtn'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_1,'router-outlet',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_20 = new import3.AppElement(20,1,this,this._el_20);
    this._RouterOutlet_20_5 = new import17.Wrapper_RouterOutlet(this.parentInjector.get(import21.RouterOutletMap),this._appEl_20.vcRef,this.parentInjector.get(import22.ComponentFactoryResolver),(null as any));
    this._text_21 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.RouterLinkWithHref) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLinkWithHref_8_3.context; }
    if (((token === import23.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3.context; }
    if (((token === import24.RouterOutlet) && (20 === requestNodeIndex))) { return this._RouterOutlet_20_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_27:any = this.context.menuState;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      var animationTransition_menuAnimation:any = this.componentType.animations['menuAnimation'](this,this._el_3,((this._expr_27 == import7.UNINITIALIZED)? 'void': this._expr_27),((currVal_27 == import7.UNINITIALIZED)? 'void': currVal_27));
      this._expr_27 = currVal_27;
    }
    const currVal_8_0_0:any = '/blogs';
    this._RouterLinkWithHref_8_3.check_routerLink(currVal_8_0_0,throwOnChange,false);
    this._RouterLinkWithHref_8_3.detectChangesInInputProps(this,this._el_8,throwOnChange);
    const currVal_11_0_0:any = '/cv';
    this._RouterLinkWithHref_11_3.check_routerLink(currVal_11_0_0,throwOnChange,false);
    this._RouterLinkWithHref_11_3.detectChangesInInputProps(this,this._el_11,throwOnChange);
    this._RouterOutlet_20_5.detectChangesInInputProps(this,this._el_20,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_28:any = import4.interpolate(1,'',this.context.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setText(this._text_6,currVal_28);
      this._expr_28 = currVal_28;
    }
    this._RouterLinkWithHref_8_3.detectChangesInHostProps(this,this._el_8,throwOnChange);
    this._RouterLinkWithHref_11_3.detectChangesInHostProps(this,this._el_11,throwOnChange);
    const currVal_29:any = import4.interpolate(1,'',this.context.menuWord,'');
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setText(this._text_18,currVal_29);
      this._expr_29 = currVal_29;
    }
    this._RouterOutlet_20_5.detectChangesInHostProps(this,this._el_20,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_8_3.context.ngOnDestroy();
    this._RouterLinkWithHref_11_3.context.ngOnDestroy();
    this._RouterOutlet_20_5.context.ngOnDestroy();
  }
  detachInternal():void {
    var animationTransition_menuAnimation:any = this.componentType.animations['menuAnimation'](this,this._el_3,this._expr_27,'void');
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_8_0:any = ((<any>this._RouterLinkWithHref_8_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_8_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_11_0:any = ((<any>this._RouterLinkWithHref_11_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_11_0);
  }
  private _handle_click_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_17_0:any = ((<any>this.context.toggleMenu()) !== false);
    return (true && pd_17_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_AppComponent,{menuAnimation: AppComponent_menuAnimation_factory})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}