/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/cv.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './views/cv.view.css.shim';
import * as import11 from '@angular/core/src/animation/animation_transition';
import * as import12 from '@angular/core/src/animation/animation_style_util';
import * as import13 from '@angular/core/src/animation/animation_sequence_player';
import * as import14 from '@angular/core/src/animation/animation_styles';
import * as import15 from '@angular/core/src/animation/animation_keyframe';
import * as import16 from '@angular/core/src/animation/animation_player';
import * as import17 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/common/src/directives/ng_if';
export class Wrapper_CvComponent {
  context:import0.CvComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.CvComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_CvComponent_Host:import2.RenderComponentType = (null as any);
class _View_CvComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _CvComponent_0_4:Wrapper_CvComponent;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CvComponent_Host0,renderType_CvComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_3 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ng-component',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CvComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CvComponent_0_4 = new Wrapper_CvComponent();
    this._appEl_0.initComponent(this._CvComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._CvComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CvComponent) && (0 === requestNodeIndex))) { return this._CvComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = this._CvComponent_0_4.context.routeAnimation;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      var animationTransition_routeAnimation:any = this._appEl_0.componentView.componentType.animations['routeAnimation'](this,this._el_0,((this._expr_3 == import7.UNINITIALIZED)? 'void': this._expr_3),((currVal_3 == import7.UNINITIALIZED)? 'void': currVal_3));
      this._expr_3 = currVal_3;
    }
    this._CvComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._CvComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  detachInternal():void {
    var animationTransition_routeAnimation:any = this._appEl_0.componentView.componentType.animations['routeAnimation'](this,this._el_0,this._expr_3,'void');
  }
}
function viewFactory_CvComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_CvComponent_Host === (null as any))) { (renderType_CvComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_CvComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const CvComponentNgFactory:import9.ComponentFactory<import0.CvComponent> = new import9.ComponentFactory<import0.CvComponent>('ng-component',viewFactory_CvComponent_Host0,import0.CvComponent);
const styles_CvComponent:any[] = [import10.styles];
var CvComponent_routeAnimation_states:any = {
  '*': {opacity: 1},
  void: {}
}
;
function CvComponent_routeAnimation_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import11.AnimationTransition {
  view.animationContext.cancelActiveAnimation(element,'routeAnimation',(nextState == 'void'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = CvComponent_routeAnimation_states['*'];
  var startStateStyles:any = CvComponent_routeAnimation_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = CvComponent_routeAnimation_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  import12.renderStyles(element,view.renderer,import12.clearStyles(startStateStyles));
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import13.AnimationSequencePlayer([view.renderer.animate(element,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {
          transform: 'translateX(-100%)',
          opacity: 0
        }

      ]
      )),import12.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import15.AnimationKeyframe(0,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[{}]))),
        new import15.AnimationKeyframe(1,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,(null as any))]);
    totalTime = 500;
  }
  if (((player == (null as any)) && (true && (nextState == 'void')))) {
      player = new import13.AnimationSequencePlayer([view.renderer.animate(element,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[startStateStyles])),[
          new import15.AnimationKeyframe(0,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[{
            transform: 'true',
            opacity: 'true'
          }
        ]))),
          new import15.AnimationKeyframe(1,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[{
            transform: 'translateX(100%)',
            opacity: 0
          }
        ])))
      ]
    ,500,0,(null as any))]);
    totalTime = 500;
  }
  if ((player == (null as any))) { (player = new import16.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    import12.renderStyles(element,view.renderer,import12.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  view.animationContext.queueAnimation(element,'routeAnimation',player);
  return new import11.AnimationTransition(player,currentState,nextState,totalTime);
}
var CvComponent_tabAnimation_states:any = {
  '*': {},
  void: {}
}
;
function CvComponent_tabAnimation_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import11.AnimationTransition {
  view.animationContext.cancelActiveAnimation(element,'tabAnimation',(nextState == 'void'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = CvComponent_tabAnimation_states['*'];
  var startStateStyles:any = CvComponent_tabAnimation_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = CvComponent_tabAnimation_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  import12.renderStyles(element,view.renderer,import12.clearStyles(startStateStyles));
  if (((player == (null as any)) && ((currentState == 'void') && true))) {
      player = new import13.AnimationSequencePlayer([view.renderer.animate(element,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {opacity: 0}
      ]
      )),[
        new import15.AnimationKeyframe(0,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[{opacity: 0}]))),
        new import15.AnimationKeyframe(1,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[{opacity: 1}])))
      ]
    ,500,0,(null as any))]);
    totalTime = 500;
  }
  if (((player == (null as any)) && (true && (nextState == 'void')))) {
      player = new import13.AnimationSequencePlayer([view.renderer.animate(element,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[startStateStyles])),[
        new import15.AnimationKeyframe(0,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[{opacity: 'true'}]))),
        new import15.AnimationKeyframe(1,new import14.AnimationStyles(import12.collectAndResolveStyles(collectedStyles,[{opacity: 0}])))
      ]
    ,500,0,(null as any))]);
    totalTime = 500;
  }
  if ((player == (null as any))) { (player = new import16.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    import12.renderStyles(element,view.renderer,import12.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  view.animationContext.queueAnimation(element,'tabAnimation',player);
  return new import11.AnimationTransition(player,currentState,nextState,totalTime);
}
var renderType_CvComponent:import2.RenderComponentType = (null as any);
class _View_CvComponent0 extends import1.AppView<import0.CvComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import17.Wrapper_NgIf;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import17.Wrapper_NgIf;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import17.Wrapper_NgIf;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import17.Wrapper_NgIf;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import17.Wrapper_NgIf;
  _text_32:any;
  _text_33:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CvComponent0,renderType_CvComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','nav'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'ul',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'li',new import4.InlineArray2(2,'style','background-color: #1ABC9C'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'基本信息',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_4,'li',new import4.InlineArray2(2,'style','background-color: #4AA3DF'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'项目经验',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_4,'li',new import4.InlineArray2(2,'style','background-color: #9B59B6'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'擅长技术',(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_4,'li',new import4.InlineArray2(2,'style','background-color: #E74C3C'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'教育经历',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,this._el_4,'li',new import4.InlineArray2(2,'style','background-color: #95A5A6'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'工作经历',(null as any));
    this._text_20 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_23 = new import3.AppElement(23,0,this,this._anchor_23);
    this._TemplateRef_23_5 = new import18.TemplateRef_(this._appEl_23,viewFactory_CvComponent1);
    this._NgIf_23_6 = new import17.Wrapper_NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_25 = new import3.AppElement(25,0,this,this._anchor_25);
    this._TemplateRef_25_5 = new import18.TemplateRef_(this._appEl_25,viewFactory_CvComponent2);
    this._NgIf_25_6 = new import17.Wrapper_NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_27 = new import3.AppElement(27,0,this,this._anchor_27);
    this._TemplateRef_27_5 = new import18.TemplateRef_(this._appEl_27,viewFactory_CvComponent3);
    this._NgIf_27_6 = new import17.Wrapper_NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_29 = new import3.AppElement(29,0,this,this._anchor_29);
    this._TemplateRef_29_5 = new import18.TemplateRef_(this._appEl_29,viewFactory_CvComponent4);
    this._NgIf_29_6 = new import17.Wrapper_NgIf(this._appEl_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_31 = new import3.AppElement(31,0,this,this._anchor_31);
    this._TemplateRef_31_5 = new import18.TemplateRef_(this._appEl_31,viewFactory_CvComponent5);
    this._NgIf_31_6 = new import17.Wrapper_NgIf(this._appEl_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import19.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import18.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import19.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6.context; }
    if (((token === import18.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import19.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6.context; }
    if (((token === import18.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import19.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    if (((token === import18.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import19.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_23_0_0:any = (this.context.currentSection == 1);
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.detectChangesInInputProps(this,this._anchor_23,throwOnChange);
    const currVal_25_0_0:any = (this.context.currentSection == 2);
    this._NgIf_25_6.check_ngIf(currVal_25_0_0,throwOnChange,false);
    this._NgIf_25_6.detectChangesInInputProps(this,this._anchor_25,throwOnChange);
    const currVal_27_0_0:any = (this.context.currentSection == 3);
    this._NgIf_27_6.check_ngIf(currVal_27_0_0,throwOnChange,false);
    this._NgIf_27_6.detectChangesInInputProps(this,this._anchor_27,throwOnChange);
    const currVal_29_0_0:any = (this.context.currentSection == 4);
    this._NgIf_29_6.check_ngIf(currVal_29_0_0,throwOnChange,false);
    this._NgIf_29_6.detectChangesInInputProps(this,this._anchor_29,throwOnChange);
    const currVal_31_0_0:any = (this.context.currentSection == 5);
    this._NgIf_31_6.check_ngIf(currVal_31_0_0,throwOnChange,false);
    this._NgIf_31_6.detectChangesInInputProps(this,this._anchor_31,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_6_0:any = ((<any>this.context.changeTab(1)) !== false);
    return (true && pd_6_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_9_0:any = ((<any>this.context.changeTab(2)) !== false);
    return (true && pd_9_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_12_0:any = ((<any>this.context.changeTab(3)) !== false);
    return (true && pd_12_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_15_0:any = ((<any>this.context.changeTab(4)) !== false);
    return (true && pd_15_0);
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_18_0:any = ((<any>this.context.changeTab(5)) !== false);
    return (true && pd_18_0);
  }
}
export function viewFactory_CvComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.CvComponent> {
  if ((renderType_CvComponent === (null as any))) { (renderType_CvComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_CvComponent,{
    routeAnimation: CvComponent_routeAnimation_factory,
    tabAnimation: CvComponent_tabAnimation_factory
  }
  )); }
  return new _View_CvComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_CvComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_28:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CvComponent1,renderType_CvComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_28 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray4(4,'class','row section','style','background-color: #1ABC9C'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','content'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'img',new import4.InlineArray4(4,'alt','','src',''),(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'刘珂',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'大风起兮云飞扬，扶摇直上九万里',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_12,'a',new import4.InlineArray2(2,'href','mailto:747311978@qq.com'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'747311978@qq.com',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_16,'a',new import4.InlineArray2(2,'href','https://github.com/harry-liu'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Github',(null as any));
    this._text_19 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'前端开发工程师',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_24 = import4.createRenderElement(this.renderer,this._el_23,'a',new import4.InlineArray2(2,'href','http://zing-studio.com.au/#/home'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Zing Studio',(null as any));
    this._text_26 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_28:any = true;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,((this._expr_28 == import7.UNINITIALIZED)? 'void': this._expr_28),((currVal_28 == import7.UNINITIALIZED)? 'void': currVal_28));
      this._expr_28 = currVal_28;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  detachInternal():void {
    var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,this._expr_28,'void');
  }
}
function viewFactory_CvComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_CvComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_CvComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_35:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CvComponent2,renderType_CvComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_35 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray4(4,'class','row section','style','background-color: #4AA3DF'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','content'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Zing Studio',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Zing Studio官方网站，Angular1',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_2,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Jmerit',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Jmerit官方网站，WordPress',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,this._el_2,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'互动圈',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'webapp，cordova+angular1',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_2,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_2,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_31 = import4.createRenderElement(this.renderer,this._el_30,'a',new import4.InlineArray2(2,'href','https://github.com/harry-liu'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Github还有更多',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_35:any = true;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,((this._expr_35 == import7.UNINITIALIZED)? 'void': this._expr_35),((currVal_35 == import7.UNINITIALIZED)? 'void': currVal_35));
      this._expr_35 = currVal_35;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  detachInternal():void {
    var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,this._expr_35,'void');
  }
}
function viewFactory_CvComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_CvComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_CvComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_34:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CvComponent3,renderType_CvComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_34 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray4(4,'class','row section','style','background-color: #9B59B6'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','content'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'CSS',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_2,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'HTML5',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_2,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Bootstrap',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_2,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_2,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_2,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'JavaScript',(null as any));
    this._text_19 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_2,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Angular 1',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_2,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Angular 2',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_2,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_2,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_2,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'jQuery',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_34:any = true;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,((this._expr_34 == import7.UNINITIALIZED)? 'void': this._expr_34),((currVal_34 == import7.UNINITIALIZED)? 'void': currVal_34));
      this._expr_34 = currVal_34;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  detachInternal():void {
    var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,this._expr_34,'void');
  }
}
function viewFactory_CvComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_CvComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_CvComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CvComponent4,renderType_CvComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_14 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray4(4,'class','row section','style','background-color: #E74C3C'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','content'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'AIT',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Bachelor Degree',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Information Technology, Software Development',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_14:any = true;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,((this._expr_14 == import7.UNINITIALIZED)? 'void': this._expr_14),((currVal_14 == import7.UNINITIALIZED)? 'void': currVal_14));
      this._expr_14 = currVal_14;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  detachInternal():void {
    var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,this._expr_14,'void');
  }
}
function viewFactory_CvComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_CvComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_CvComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_23:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CvComponent5,renderType_CvComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_23 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray4(4,'class','row section','style','background-color: #95A5A6'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','content'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'澳洲门道',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'实习生，前端程序员',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Zing Studio',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'创始人之一，rogrammer',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_2,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'互动未来',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'前端程序员',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_23:any = true;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,((this._expr_23 == import7.UNINITIALIZED)? 'void': this._expr_23),((currVal_23 == import7.UNINITIALIZED)? 'void': currVal_23));
      this._expr_23 = currVal_23;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  detachInternal():void {
    var animationTransition_tabAnimation:any = this.componentType.animations['tabAnimation'](this,this._el_0,this._expr_23,'void');
  }
}
function viewFactory_CvComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_CvComponent5(viewUtils,parentInjector,declarationEl);
}